"""Lifecycle event dispatcher.

:class:`LifecycleDispatcher` is the bridge between
:class:`~src.vendors.ticketmaster.core.BotRunner` (the producer of
lifecycle events) and :class:`~src.hooks.base.Hook` instances (the
consumers).

The full set of lifecycle event names is published in
:data:`LIFECYCLE_EVENTS`. The dispatcher rejects unknown names so a
typo at a call site fails loudly instead of silently dropping the
event. Hook errors are logged but do not abort the dispatch: a failing
observer must not break the runner's main flow.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..hooks.base import HookRegistry

log = logging.getLogger("ticketmaster-bot")


#: Every lifecycle event the runner may fire, in the order they
#: appear in a successful end-to-end run. Listed explicitly (rather
#: than autogenerated from an enum) so the orchestrator's contract is
#: greppable and the test in
#: ``tests/hooks/test_lifecycle.py`` can pin the canonical order.
LIFECYCLE_EVENTS: tuple[str, ...] = (
    "on_run_start",
    "before_login",
    "after_login",
    "before_navigate",
    "after_queue_release",
    "before_select",
    "after_select",
    "before_cart",
    "after_cart",
    "before_checkout",
    "before_place_order",
    "on_failure",
    "on_run_end",
)


_LIFECYCLE_EVENTS_SET: frozenset[str] = frozenset(LIFECYCLE_EVENTS)


class LifecycleDispatcher:
    """Dispatches lifecycle events to every hook registered on a runner.

    Parameters
    ----------
    registry:
        The :class:`~src.hooks.base.HookRegistry` carrying the hooks
        this dispatcher should drive. Each
        :class:`~src.vendors.ticketmaster.core.BotRunner` owns its own
        registry + dispatcher pair so multi-account / parallel runs do
        not share hook state.
    """

    def __init__(self, registry: HookRegistry) -> None:
        self.registry = registry

    async def fire(self, event_type: str, ctx: Any, **kwargs: Any) -> None:
        """Fire ``event_type`` on every enabled hook, in priority order.

        Parameters
        ----------
        event_type:
            One of :data:`LIFECYCLE_EVENTS`. Anything else raises
            :class:`ValueError`.
        ctx:
            Context object handed to every hook's
            :meth:`~src.hooks.base.Hook.on_event` call. The production
            runner passes ``self`` so hooks can read configuration and
            mutate runtime parameters (e.g. ``action_delay_min``).
        kwargs:
            Per-event payload forwarded verbatim to every hook.

        Raises
        ------
        ValueError:
            If ``event_type`` is not in :data:`LIFECYCLE_EVENTS`.
        """
        if event_type not in _LIFECYCLE_EVENTS_SET:
            raise ValueError(
                f"unknown lifecycle event {event_type!r}; "
                f"expected one of {LIFECYCLE_EVENTS}"
            )
        for hook in self.registry.all():
            if not hook.enabled:
                continue
            try:
                await hook.on_event(ctx, event_type, **kwargs)
            except Exception:
                log.exception(
                    "Hook %r raised while handling %r; continuing",
                    hook.__class__.__name__,
                    event_type,
                )


__all__ = ["LIFECYCLE_EVENTS", "LifecycleDispatcher"]
